FROM node:22-alpine

LABEL maintainer=github/rickli-cloud

ENV NODE_ENV development

RUN apk add git

WORKDIR /work

COPY package*.json .
COPY . .

EXPOSE 5173

CMD [ "/bin/sh", "-c", "npm install; sleep infinity" ]
