/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { HttpResponse, http } from 'msw';
import { faker } from '@faker-js/faker';
import type { components } from '$lib/api';

faker.seed(1);

const baseURL = '';
const MAX_ARRAY_LENGTH = 5;

let i = 0;
const next = () => {
	if (i === Number.MAX_SAFE_INTEGER - 1) {
		i = 0;
	}
	return i++;
};

export const handlers = [
	http.get(`${baseURL}/api/v1/apikey`, async () => {
		const resultArray = [
			[await getHeadscaleServiceListApiKeys200Response(), { status: 200 }],
			[await getHeadscaleServiceListApiKeysdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/apikey`, async () => {
		const resultArray = [
			[await getHeadscaleServiceCreateApiKey200Response(), { status: 200 }],
			[await getHeadscaleServiceCreateApiKeydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/apikey/expire`, async () => {
		const resultArray = [
			[await getHeadscaleServiceExpireApiKey200Response(), { status: 200 }],
			[await getHeadscaleServiceExpireApiKeydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.delete(`${baseURL}/api/v1/apikey/:prefix`, async () => {
		const resultArray = [
			[await getHeadscaleServiceDeleteApiKey200Response(), { status: 200 }],
			[await getHeadscaleServiceDeleteApiKeydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/debug/node`, async () => {
		const resultArray = [
			[await getHeadscaleServiceDebugCreateNode200Response(), { status: 200 }],
			[await getHeadscaleServiceDebugCreateNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/node`, async () => {
		const resultArray = [
			[await getHeadscaleServiceListNodes200Response(), { status: 200 }],
			[await getHeadscaleServiceListNodesdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/node/backfillips`, async () => {
		const resultArray = [
			[await getHeadscaleServiceBackfillNodeIPs200Response(), { status: 200 }],
			[await getHeadscaleServiceBackfillNodeIPsdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/node/register`, async () => {
		const resultArray = [
			[await getHeadscaleServiceRegisterNode200Response(), { status: 200 }],
			[await getHeadscaleServiceRegisterNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/node/:nodeId`, async () => {
		const resultArray = [
			[await getHeadscaleServiceGetNode200Response(), { status: 200 }],
			[await getHeadscaleServiceGetNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.delete(`${baseURL}/api/v1/node/:nodeId`, async () => {
		const resultArray = [
			[await getHeadscaleServiceDeleteNode200Response(), { status: 200 }],
			[await getHeadscaleServiceDeleteNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/node/:nodeId/expire`, async () => {
		const resultArray = [
			[await getHeadscaleServiceExpireNode200Response(), { status: 200 }],
			[await getHeadscaleServiceExpireNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/node/:nodeId/rename/:newName`, async () => {
		const resultArray = [
			[await getHeadscaleServiceRenameNode200Response(), { status: 200 }],
			[await getHeadscaleServiceRenameNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/node/:nodeId/routes`, async () => {
		const resultArray = [
			[await getHeadscaleServiceGetNodeRoutes200Response(), { status: 200 }],
			[await getHeadscaleServiceGetNodeRoutesdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/node/:nodeId/tags`, async () => {
		const resultArray = [
			[await getHeadscaleServiceSetTags200Response(), { status: 200 }],
			[await getHeadscaleServiceSetTagsdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/node/:nodeId/user`, async () => {
		const resultArray = [
			[await getHeadscaleServiceMoveNode200Response(), { status: 200 }],
			[await getHeadscaleServiceMoveNodedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/policy`, async () => {
		const resultArray = [
			[await getHeadscaleServiceGetPolicy200Response(), { status: 200 }],
			[await getHeadscaleServiceGetPolicydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.put(`${baseURL}/api/v1/policy`, async () => {
		const resultArray = [
			[await getHeadscaleServiceSetPolicy200Response(), { status: 200 }],
			[await getHeadscaleServiceSetPolicydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/preauthkey`, async () => {
		const resultArray = [
			[await getHeadscaleServiceListPreAuthKeys200Response(), { status: 200 }],
			[await getHeadscaleServiceListPreAuthKeysdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/preauthkey`, async () => {
		const resultArray = [
			[await getHeadscaleServiceCreatePreAuthKey200Response(), { status: 200 }],
			[await getHeadscaleServiceCreatePreAuthKeydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/preauthkey/expire`, async () => {
		const resultArray = [
			[await getHeadscaleServiceExpirePreAuthKey200Response(), { status: 200 }],
			[await getHeadscaleServiceExpirePreAuthKeydefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/routes`, async () => {
		const resultArray = [
			[await getHeadscaleServiceGetRoutes200Response(), { status: 200 }],
			[await getHeadscaleServiceGetRoutesdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.delete(`${baseURL}/api/v1/routes/:routeId`, async () => {
		const resultArray = [
			[await getHeadscaleServiceDeleteRoute200Response(), { status: 200 }],
			[await getHeadscaleServiceDeleteRoutedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/routes/:routeId/disable`, async () => {
		const resultArray = [
			[await getHeadscaleServiceDisableRoute200Response(), { status: 200 }],
			[await getHeadscaleServiceDisableRoutedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/routes/:routeId/enable`, async () => {
		const resultArray = [
			[await getHeadscaleServiceEnableRoute200Response(), { status: 200 }],
			[await getHeadscaleServiceEnableRoutedefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/user`, async () => {
		const resultArray = [
			[await getHeadscaleServiceListUsers200Response(), { status: 200 }],
			[await getHeadscaleServiceListUsersdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/user`, async () => {
		const resultArray = [
			[await getHeadscaleServiceCreateUser200Response(), { status: 200 }],
			[await getHeadscaleServiceCreateUserdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.get(`${baseURL}/api/v1/user/:name`, async () => {
		const resultArray = [
			[await getHeadscaleServiceGetUser200Response(), { status: 200 }],
			[await getHeadscaleServiceGetUserdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.delete(`${baseURL}/api/v1/user/:name`, async () => {
		const resultArray = [
			[await getHeadscaleServiceDeleteUser200Response(), { status: 200 }],
			[await getHeadscaleServiceDeleteUserdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	}),
	http.post(`${baseURL}/api/v1/user/:oldName/rename/:newName`, async () => {
		const resultArray = [
			[await getHeadscaleServiceRenameUser200Response(), { status: 200 }],
			[await getHeadscaleServiceRenameUserdefaultResponse(), { status: NaN }]
		];

		return HttpResponse.json(...resultArray[next() % resultArray.length]);
	})
];

export function getHeadscaleServiceListApiKeys200Response() {
	return {
		apiKeys: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			id: faker.number.octal(),
			prefix: faker.lorem.words(),
			expiration: faker.date.past(),
			createdAt: faker.date.past(),
			lastSeen: faker.date.past()
		}))
	};
}

export function getHeadscaleServiceListApiKeysdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceCreateApiKey200Response() {
	return {
		apiKey: faker.lorem.words()
	};
}

export function getHeadscaleServiceCreateApiKeydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceExpireApiKey200Response() {
	return {};
}

export function getHeadscaleServiceExpireApiKeydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceDeleteApiKey200Response() {
	return {};
}

export function getHeadscaleServiceDeleteApiKeydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceDebugCreateNode200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceDebugCreateNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceListNodes200Response() {
	return {
		nodes: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}))
	};
}

export function getHeadscaleServiceListNodesdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceBackfillNodeIPs200Response() {
	return {
		changes: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
	};
}

export function getHeadscaleServiceBackfillNodeIPsdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceRegisterNode200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceRegisterNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceGetNode200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceGetNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceDeleteNode200Response() {
	return {};
}

export function getHeadscaleServiceDeleteNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceExpireNode200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceExpireNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceRenameNode200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceRenameNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceGetNodeRoutes200Response() {
	return {
		routes: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			id: faker.number.octal(),
			node: {
				id: faker.number.octal(),
				machineKey: faker.lorem.words(),
				nodeKey: faker.lorem.words(),
				discoKey: faker.lorem.words(),
				ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				name: faker.person.fullName(),
				user: {
					id: faker.number.octal(),
					name: faker.person.fullName(),
					createdAt: faker.date.past()
				},
				lastSeen: faker.date.past(),
				expiry: faker.date.past(),
				preAuthKey: {
					user: faker.lorem.words(),
					id: faker.number.octal(),
					key: faker.lorem.words(),
					reusable: faker.datatype.boolean(),
					ephemeral: faker.datatype.boolean(),
					used: faker.datatype.boolean(),
					expiration: faker.date.past(),
					createdAt: faker.date.past(),
					aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
				},
				createdAt: faker.date.past(),
				registerMethod: faker.helpers.arrayElement([
					'REGISTER_METHOD_UNSPECIFIED',
					'REGISTER_METHOD_AUTH_KEY',
					'REGISTER_METHOD_CLI',
					'REGISTER_METHOD_OIDC'
				]),
				forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				givenName: faker.person.fullName(),
				online: faker.datatype.boolean()
			},
			prefix: faker.lorem.words(),
			advertised: faker.datatype.boolean(),
			enabled: faker.datatype.boolean(),
			isPrimary: faker.datatype.boolean(),
			createdAt: faker.date.past(),
			updatedAt: faker.date.past(),
			deletedAt: faker.date.past()
		}))
	};
}

export function getHeadscaleServiceGetNodeRoutesdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceSetTags200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceSetTagsdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceMoveNode200Response() {
	return {
		node: {
			id: faker.number.octal(),
			machineKey: faker.lorem.words(),
			nodeKey: faker.lorem.words(),
			discoKey: faker.lorem.words(),
			ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			name: faker.person.fullName(),
			user: {
				id: faker.number.octal(),
				name: faker.person.fullName(),
				createdAt: faker.date.past()
			},
			lastSeen: faker.date.past(),
			expiry: faker.date.past(),
			preAuthKey: {
				user: faker.lorem.words(),
				id: faker.number.octal(),
				key: faker.lorem.words(),
				reusable: faker.datatype.boolean(),
				ephemeral: faker.datatype.boolean(),
				used: faker.datatype.boolean(),
				expiration: faker.date.past(),
				createdAt: faker.date.past(),
				aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
			},
			createdAt: faker.date.past(),
			registerMethod: faker.helpers.arrayElement([
				'REGISTER_METHOD_UNSPECIFIED',
				'REGISTER_METHOD_AUTH_KEY',
				'REGISTER_METHOD_CLI',
				'REGISTER_METHOD_OIDC'
			]),
			forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
			givenName: faker.person.fullName(),
			online: faker.datatype.boolean()
		}
	};
}

export function getHeadscaleServiceMoveNodedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceGetPolicy200Response() {
	return {
		policy: faker.lorem.words(),
		updatedAt: faker.date.past()
	};
}

export function getHeadscaleServiceGetPolicydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceSetPolicy200Response() {
	return {
		policy: faker.lorem.words(),
		updatedAt: faker.date.past()
	};
}

export function getHeadscaleServiceSetPolicydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceListPreAuthKeys200Response() {
	return {
		preAuthKeys: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			user: faker.lorem.words(),
			id: faker.number.octal(),
			key: faker.lorem.words(),
			reusable: faker.datatype.boolean(),
			ephemeral: faker.datatype.boolean(),
			used: faker.datatype.boolean(),
			expiration: faker.date.past(),
			createdAt: faker.date.past(),
			aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
		}))
	};
}

export function getHeadscaleServiceListPreAuthKeysdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceCreatePreAuthKey200Response() {
	return {
		preAuthKey: {
			user: faker.lorem.words(),
			id: faker.number.octal(),
			key: faker.lorem.words(),
			reusable: faker.datatype.boolean(),
			ephemeral: faker.datatype.boolean(),
			used: faker.datatype.boolean(),
			expiration: faker.date.past(),
			createdAt: faker.date.past(),
			aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
		}
	};
}

export function getHeadscaleServiceCreatePreAuthKeydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceExpirePreAuthKey200Response() {
	return {};
}

export function getHeadscaleServiceExpirePreAuthKeydefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceGetRoutes200Response() {
	return {
		routes: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			id: faker.number.octal(),
			node: {
				id: faker.number.octal(),
				machineKey: faker.lorem.words(),
				nodeKey: faker.lorem.words(),
				discoKey: faker.lorem.words(),
				ipAddresses: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				name: faker.person.fullName(),
				user: {
					id: faker.number.octal(),
					name: faker.person.fullName(),
					createdAt: faker.date.past()
				},
				lastSeen: faker.date.past(),
				expiry: faker.date.past(),
				preAuthKey: {
					user: faker.lorem.words(),
					id: faker.number.octal(),
					key: faker.lorem.words(),
					reusable: faker.datatype.boolean(),
					ephemeral: faker.datatype.boolean(),
					used: faker.datatype.boolean(),
					expiration: faker.date.past(),
					createdAt: faker.date.past(),
					aclTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words())
				},
				createdAt: faker.date.past(),
				registerMethod: faker.helpers.arrayElement([
					'REGISTER_METHOD_UNSPECIFIED',
					'REGISTER_METHOD_AUTH_KEY',
					'REGISTER_METHOD_CLI',
					'REGISTER_METHOD_OIDC'
				]),
				forcedTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				invalidTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				validTags: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => faker.lorem.words()),
				givenName: faker.person.fullName(),
				online: faker.datatype.boolean()
			},
			prefix: faker.internet.ipv4() + '/32',
			advertised: faker.datatype.boolean(),
			enabled: faker.datatype.boolean(),
			isPrimary: faker.datatype.boolean(),
			createdAt: faker.date.past(),
			updatedAt: faker.date.past(),
			deletedAt: undefined
		}))
	};
}

export function getHeadscaleServiceGetRoutesdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceDeleteRoute200Response() {
	return {};
}

export function getHeadscaleServiceDeleteRoutedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceDisableRoute200Response() {
	return {};
}

export function getHeadscaleServiceDisableRoutedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceEnableRoute200Response() {
	return {};
}

export function getHeadscaleServiceEnableRoutedefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceListUsers200Response() {
	return {
		users: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			id: faker.number.octal(),
			name: faker.person.fullName(),
			createdAt: faker.date.past()
		}))
	};
}

export function getHeadscaleServiceListUsersdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceCreateUser200Response() {
	return {
		user: {
			id: faker.number.octal(),
			name: faker.person.fullName(),
			createdAt: faker.date.past()
		}
	};
}

export function getHeadscaleServiceCreateUserdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceGetUser200Response() {
	return {
		user: {
			id: faker.number.octal(),
			name: faker.person.fullName(),
			createdAt: faker.date.past()
		}
	};
}

export function getHeadscaleServiceGetUserdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceDeleteUser200Response() {
	return {};
}

export function getHeadscaleServiceDeleteUserdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}

export function getHeadscaleServiceRenameUser200Response() {
	return {
		user: {
			id: faker.number.octal(),
			name: faker.person.fullName(),
			createdAt: faker.date.past()
		}
	};
}

export function getHeadscaleServiceRenameUserdefaultResponse() {
	return {
		code: faker.number.int(),
		message: faker.lorem.words(),
		details: [...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys()].map((_) => ({
			'@type': faker.lorem.words()
		}))
	};
}
